#cloud-config

package_update: true
package_upgrade: true

packages:
  - curl
  - apt-transport-https
  - ca-certificates
  - gnupg2
  - software-properties-common

runcmd:
  - curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
  - echo 'deb [arch=amd64] https://download.docker.com/linux/debian buster stable' | tee /etc/apt/sources.list.d/docker.list
  - apt update
  - apt install -y docker-ce docker-ce-cli containerd.io
  - systemctl enable docker
  - systemctl start docker 
